# Generated by Django 3.1.3 on 2021-07-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.TextField(default='default'),
        ),
    ]
